public/index.html
=> Updated title for inventorycount(#1w9gm4n)

public/index.html
Improved title for the app
Closes #
=> Updated title for the app

changelogs/unreleased/-1y2ract.yml, src/views/Settings.vue
=> Updated the markup(#1y2ract)

changelogs/unreleased/-47gzm1.yml, package-lock.json, package.json, src/components/Scanner.vue, src/views/Search.vue
=> Added support to search products by scanning barcode(#47gzm1)

android/app/src/main/assets/capacitor.config.json, capacitor.config.json, ios/App/App/capacitor.config.json, package-lock.json, package.json
Closes #
Changed app name from ionic-sdk to inventory-count
Updated version to 1.0.0
Synced android and ios builds using `npx cap sync android` and `npx cap sync ios`
=> Improved: app name and version of the app

changelogs/unreleased/-2401fr1.yml, src/App.vue, src/views/Search.vue, src/views/Upload.vue
=> Removed fab position adjustment and decreased value of bottom position of scan button (#2401fr1)

README.md
=> Add image banner

changelogs/unreleased/-1zawzz8.yml, package-lock.json, package.json
=> Upgraded the version of vue barcode reader(#1zawzz8)

README.md
=> Improved instructions

changelogs/unreleased/-1zax3p6.yml, src/main.ts
=> Added md mode (#1zax3p6)

changelogs/unreleased/-1zaxn7d.yml, src/views/Search.vue
https://app.clickup.com/t/1zaxn7d
Closes https://app.clickup.com/t/1zaxn7d
=> Improved position of scan button on search page (#1zaxn7d)

.github/workflows/pull-request.yml
=> Added configuration to verify build on PR and commit

src/views/Upload.vue
=> Added: static value for the locationId when uploading products

changelogs/unreleased/-238tkgm.yml, src/components/ProductListItem.vue, src/views/count.vue
=> Implemented logic to handle product with no features(#238tkgm)

src/components/Scanner.vue
=> Improved markup of scanner modal(#238t4a0)

public/index.html
=> Added theme Color in index.html(#226cynn)

src/router/index.ts, src/views/Search.vue
This reverts commit 1e16e9ed541a1d0a911a3e1109ab43c1f5c7978a.
Closes #
=> Revert "Deleted extra search page from inventory-count(#23eera9)"

changelogs/unreleased/-22qm8pq.yml, src/locales/en.json, src/services/UserService.ts, src/store/modules/user/actions.ts, src/views/Upload.vue, src/views/count.vue
=> Impelented: logic to select location on pdp page(#22qm8pq)

src/views/Search.vue
Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.
=> Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

package-lock.json, package.json
=> Improved: app version in package and lock file for new release(#2rbz0yh)

release-notes.md
=> Prepared for release 1.0.1

package-lock.json, package.json
=> Upgraded ionic to 6.1.15(#2uaz29u)

package-lock.json, package.json
=> Upgraded ionic to 6.2(#2w9wz26)

release-notes.md
=> Prepare for the release 1.1.0

package-lock.json, package.json
=> Preparing for release 1.1.0

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release

src/views/Upload.vue
Closes #104 
Disabled the upload floating action button when no products are there to upload.
=> Updated code to disable the upload button when no products to upload (#85zrjcac7)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.3.0)

release-notes.md
=> Preparing for the release

src/store/modules/product/actions.ts, src/views/Search.vue
=> Added support to scan products with all the product identifications (#85zrjbtxf)

src/store/modules/product/actions.ts
=> fix: searched products not cleared if product not found on scanning or searching(#85zrkjneg)

src/components/Scanner.vue
Closes #131 
Removed unwanted code as we were not performing any computation on onLoaded event. 
=> fix: warning in console when clicking scan button(#85zrkj2ud)

src/store/modules/user/actions.ts, src/store/modules/user/mutations.ts, src/views/Search.vue
=> Fixed: search products not cleared on logout(#85zrjbxux)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release v1.4.0

src/components/Scanner.vue, src/locales/en.json, src/views/Search.vue
Closes #130 
[Screencast from 03-02-23 04:32:03 PM IST.webm](https://user-images.githubusercontent.com/59442907/216587539-3637f14f-eb9c-4797-9cd0-d5fffeee0421.webm)
=> Implemented: Toast notification when camera permission is denied for scanner (#85zrk1af8)

.eslintrc.js, src/App.vue, src/components/ProductListItem.vue, src/services/ProductService.ts, src/views/Search.vue, src/views/count.vue
Closes #165 
[Screencast from 05-04-23 12:17:57 PM IST.webm](https://user-images.githubusercontent.com/59442907/230002591-72b3c157-1eaf-479a-8d78-db9747a41eb4.webm)
=> Fixed: Product data not fetched on refresh (#85zrvh9we)

src/store/modules/user/actions.ts
=> Fixed: missing facilities causing sideeffects when userprofile response is delayed

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.6.0)

src/locales/en.json, src/views/Upload.vue
=> Implemented: confirmation alert on inventory count upload (#85zrx64et)

.github/PULL_REQUEST_TEMPLATE.md
=> Improved: PR template by fixing typos, links and removed unwanted checks

package-lock.json, package.json
=> Updated: app version for minor release (1.8.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.9.0)

package-lock.json, package.json, release-notes.md
=> Updated: app version for minor release (1.10.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.11.0)

package-lock.json, package.json
=> Updated: package.json and package-lock.json for minor release v1.13.0

package-lock.json, package.json
=> Updated: app version for patch release(v1.14.1)

package-lock.json, package.json
Closes #
Updated: app version for the minor release (1.15.0).
=> Updated: app version for the minor release (1.15.0).

package-lock.json, package.json
Closes #
Updated: app version for the patch release (v1.15.1).
=> Updated: app version for the patch release (v1.15.1).

src/store/modules/product/actions.ts
Closes #
Fixed solr query for fetching products on count page.
=> Fixed: solr query for fetching products on count page

src/services/ProductService.ts, src/views/count.vue
Closes #256
Added supoort to create product facility location after product association with the facility. This way we can get the locationId for the product.
=> Improved: added support to create product facility location (#256)

package-lock.json, package.json
=> Updated: app version for patch release (v1.15.2)

src/views/Upload.vue
=> Fixed: pointer not visible on hovering over the card on upload page by adding button attribute on ion-card

src/views/count.vue
=> Improved: support to update the variance on stock input(#245)

package-lock.json, package.json
Closes #
Updated: app version for the minor release (v1.16.0).
=> Updated: app version for the minor release (v1.16.0).

package-lock.json, package.json
=> Improved: dxp version to latest for fixing the goToOMS redirection(dxp/275)

src/App.vue, src/components/AssignedCountPopover.vue, src/components/DraftsFilter.vue, src/components/Menu.vue, src/router/index.ts, src/theme/variables.css, src/views/Assigned.vue, src/views/AssignedCount.vue, src/views/DraftCount.vue, src/views/Drafts.vue
Closes #285 
- Implemented the assigned page with popover.
- Implemented the details page for the assigned page.
=> Implemented: Assigned page, popover and assigned count page(#285)

src/components/Filters.vue, src/router/index.ts, src/services/CountService.ts, src/store/modules/count/CountState.ts, src/store/modules/count/actions.ts, src/store/modules/count/getters.ts, src/store/modules/count/index.ts, src/store/modules/count/mutation-types.ts, src/store/modules/count/mutations.ts, src/utils/index.ts, src/views/Draft.vue, src/views/DraftDetail.vue, src/views/PendingReview.vue
=> Implemented: support to make the pending review list dynamic and added support to display the count stats(#301)

src/views/Closed.vue, src/views/Draft.vue
=> Implemented: support to make the closed list page dynamic(#307)

src/utils/index.ts
=> Improved: utility function to return derived status based on count status and countStats

src/services/UserService.ts, src/store/modules/user/actions.ts
=> Fixed: issue of request url is not formed correctly when feching permissions(#312)

src/services/CountService.ts, src/utils/index.ts, src/views/Assigned.vue, src/views/PendingReview.vue
=> Improved: stats api payload and added checks for color on the status badge

src/services/CountService.ts, src/store/modules/count/actions.ts, src/views/Count.vue, src/views/CountDetail.vue, src/views/ProductDetail.vue, src/views/ProductItemList.vue
=> Improved: UI to display some missing information on UI, updated stats api and improved checks for dispalying item status on picker screen

src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue, src/views/ProductItemList.vue
=> Improved: UI for draft detail page and improved logic to accept or reject item based on variance threshold

src/utils/index.ts, src/views/AssignedDetail.vue, src/views/Closed.vue, src/views/Count.vue, src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue, src/views/ProductDetail.vue
#
Improved: api payload when marking items as completed, used partyName method for displaying user name, fixed issue to not mark buttons to be primary action, and improved statusId payload on closed page
=> Improved: method to define derived status based on count status and implemented method to display partyName on UI

src/components/AddProductModal.vue, src/components/Filters.vue, src/locales/en.json, src/store/modules/user/actions.ts, src/views/Assigned.vue, src/views/AssignedDetail.vue, src/views/Closed.vue, src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue, src/views/ProductDetail.vue, src/views/ProductItemList.vue, src/views/Tabs.vue
=> Fixed: items information not updated after marking items as accepted

src/App.vue
=> Fixed: issue on menu not visible on first load of the app(#335)

src/views/ProductItemList.vue, src/views/Settings.vue
=> Implemented: support to display app version info on settings page

src/store/modules/user/actions.ts, src/views/Settings.vue
=> Fixed: issue when facility is not associated with a product store

src/views/PendingReviewDetail.vue
=> Fixed: issue of variance threshold calculation by adding brackets when calculating percentage(#362)

src/components/AssignedCountPopover.vue
=> Fixed: primary identifier not displayed inside the popover on assigned page(#358)

src/views/DraftDetail.vue
=> Removed rejection history chip from the draf detail page(#350)

src/views/PendingReviewDetail.vue
#361 
- Improved logic to select items from the current segment only on clicking selectAll button
- Added support to select/unselect all items using selectAll button
=> Implemented: support to select and unselect items, and only allow selection of items in the current segment(#361)

src/views/AssignedDetail.vue, src/views/PendingReviewDetail.vue
=> Implemented: support to change the count dueDate from assigned and pendingReview detail page(#351)

src/locales/en.json, src/views/DraftDetail.vue
=> Improved: input field to display helper text regarding field on the basis of which products are searched(#347)

src/views/AssignedDetail.vue, src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue
=> Fixed: case to remove emitter registration when leaving the page, as this results in multiple api calls being made when adding a new product to count

src/locales/en.json, src/views/ProductDetail.vue
=> Implemented: toast message to be displayed when trying to save a product with empty count

src/views/CountDetail.vue
=> Improved: check to display the readyForReview option only for counts having assigned status(#381)

src/views/DraftDetail.vue
#349 
Removed debounce property from ion-input and added a watcher to implement the debounce effect
=> Improved: code to display spinner as soon as user starts searching and clear search result when input is empty(#349)

src/views/ProductDetail.vue
#393 
- Added a check in the Count Detail section to prevent negative values for the item count.
=> Improved: User is not able to save the negative value for the item count(#393)

src/views/ProductDetail.vue
#377
- Added a quantity check for 0 value in Inventory count.
=> Improved: item with a 0 inventory count should be saved correctly and will not be pending in the Assigned section(#377)

src/views/Assigned.vue, src/views/Closed.vue, src/views/Draft.vue, src/views/PendingReview.vue
=> Improved: hook to use unmounted hook for clearing filter params

src/router/index.ts, src/views/Assigned.vue, src/views/Closed.vue, src/views/Draft.vue, src/views/PendingReview.vue
=> Improved: logic to clear the filters

src/components/DownloadClosedCountModal.vue, src/views/Closed.vue
=> Improved: logic to filter the download data based on the filters selected on the page and disable download button if counts are not available

src/components/DownloadClosedCountModal.vue
#341 
- Changed the sequence of column names in the CSV by altering the mapping and object fields.
- Removed the facility name from the downloaded CSV and now the updated name will have `CycleCounts - current date.csv`
=> Improved: Changed the sequence of column names in the CSV and removed the facility name from the downloaded CSV(#341)

src/views/DraftDetail.vue
#407
When uploading items using CSV we were not passing the status of the item being uploaded, so added the field of statusId on upload items.
=> Fixed: issue of items not being selected on review page after being uploaded using csv(#407)

src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue
=> Improved: template by moving color property from icon to button when icon

src/views/DraftDetail.vue
=> Improved: code to display toast when products are not being added in the count

src/views/PendingReviewDetail.vue
#419 
Used two way binding to update the threshold value in real-time and remove the change event defined on the slider
=> Improved: UI to make the threshold value change in real time by using two-way binding and removing the change event from the slider(#419)

src/components/Filters.vue
=> Implemented: support to display selected facilities in the filters on the closed page(#420)

src/theme/variables.css, src/views/AssignedDetail.vue, src/views/PendingReviewDetail.vue, src/views/ProductDetail.vue
=> Improved: styling for the icons and added spacing on the UI

src/views/CountDetail.vue
#397 
- Added the changes of product details component to the count detail component , which addresses some of minor issues.
- Includes error handling using toast messages, checks on button and validation on the input count.
=> Improved: added the changes from productDetail to countDetail component(#397)

src/services/CountService.ts, src/views/AssignedDetail.vue, src/views/CountDetail.vue, src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue
#357 
- Resolve the issue of clicking Recount button results in UI distortion.
- Added the support of viewSize , when fetching the items.
=> Improved: added viewSize while fetching items &  resolve UI distortion(#357)

src/components/AddProductModal.vue, src/views/ProductDetail.vue
#338 
- Displayed an empty state message when no products are found.
- Showed a different empty state message depending on whether the user has searched for a product or not.
=> Improved: Displayed an empty state message or UI element indicating no products match the search criteria(#338)

src/components/Filters.vue, src/locales/en.json
=> Improved: UI when displaying selected facilities on the completed page filter(#420)

package-lock.json, package.json
#
Updated: app version for major release (v2.0.0)
=> Updated: app version for major release (v2.0.0)

src/views/DraftDetail.vue
#
Improved: searching on draft detail page to make exact search using sku as when using like-wise searching, if the sku searched is a subset of another sku then the results are displayed as expected
=> Improved: searching on draft detail page to make exact search using sku

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v2.1.0)

package-lock.json, package.json
=> Updated: app version for patch release v2.1.1

src/locales/en.json, src/views/BulkUpload.vue
#451
#
Improved: Corrected validation message (#451).
=> Improved: Corrected validation message (#451).

package-lock.json, package.json
=> Updated: app version for the patch release v2.1.2.

src/views/BulkUpload.vue
#437 
#
Fixed: Passed default inventory count import status Id (#437).
=> Fixed: Passed default inventory count import status Id (#437).

src/views/Assigned.vue, src/views/Closed.vue, src/views/Draft.vue, src/views/PendingReview.vue
#471 
- Added unique id to all the ion-menu in different page to fix menu referencing issue in case of multiple ion-menu.
=> Fixed: multiple menu opening issue by giving unique id to each menu (#471)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v2.2.0)

src/views/CountDetail.vue
#
Fixed undefined passing in object error in count details page
=> Fixed: undefined passing in object error in count details page

src/views/PendingReviewDetail.vue
=> Fixed:  Only Current Year (2024) Visible for Due Date Selection in Draft, Assigned, or Pending Review Tab (#470)

package-lock.json, package.json
=> Updated: app version for the minor release (v2.3.0)

src/views/CountDetail.vue
#494
Improved the icon used and the styling over the button in the scroll up/down button.
=> Improved: icons and styling over the scrolling button (#494-scroll)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.3.1)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.3.2)

src/views/CountDetail.vue
=> Reverted: resetting of the inputCount on product change (#494)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.3.3)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.3.4)

src/views/CountDetail.vue
#494
Autofocusing the product search bar on entering the detail page for the first time or reloading.
=> Improved: autofocusing searchbar on the page reload (#494)

package-lock.json, package.json
=> Updated: app version for minor release v2.4.0.

src/store/modules/user/actions.ts
=> Fixed: logger error message when fetching product stores

src/views/AssignedDetail.vue, src/views/DraftDetail.vue, src/views/HardCountDetail.vue, src/views/PendingReviewDetail.vue
#528
Added pagination while fetching cycle count items in the admin screen.
=> Implemented: pagination while fetching cycle count items in the admin screen (#528)

src/views/HardCountDetail.vue
#528
Clearing input count post updation of items in the cycle count.
=> Fixed: clearing inputCount post list updation in state (#528-bugs)

src/views/HardCountDetail.vue
#528
Fixed current count getting added twice.
=> Fixed: scanned count getting saved twice in the list state (#528)

src/store/modules/count/CountState.ts, src/store/modules/count/getters.ts, src/store/modules/count/index.ts, src/views/HardCountDetail.vue
#528
Support for default recount updation behaviour and resetting to it on each product
=> Improved: added support for default recount updation behaviour and reseting to it on each product (#528)

src/components/DownloadClosedCountModal.vue
=> Fixed: issue in download csv file to use item status

package-lock.json, package.json
=> Updated: app version for the minor release (v2.5.0)

src/components/MatchProductModal.vue
#558
Payload for searching product to not search based on parent product.
=> Improved: payload for searching product to not search on parent (#558)

src/components/MatchProductModal.vue
#562
Changed the UI of the already added item in the match product modal.
=> Improved: UI of the already selected item in the count item in match product modal (#562)

src/views/HardCountDetail.vue
#556
Changed the product item list component key while rendering a list for unique identification (#556)
=> Fixed: image not updating in list for unmatched items on segment change (#556)

src/views/HardCount.vue
#587
Added validation to not allow create hard count without name.
=> Improved: added validation to not allow user to create hard count without name (#587)

src/views/HardCount.vue
#528
Resetting the filtered facilities on changing the segment.
=> Improved: reseting the filtered facilities on segment change (#528)

src/views/CountDetail.vue
#528
Added a check for cycle count status to make counting work only in case of assigned count.
=> Fixed: recount alert opening in case of pending review counts with created item (#528)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.5.1)

src/views/DraftDetail.vue
#555
Enhanced the empty state message.
=> Improved: empty state message for no items in the draft detail page (#555)

src/views/HardCountDetail.vue, src/views/ProductItemList.vue
=> Fixed: wrong button getting displayed in case of unmatched product (#528)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.5.2)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.5.3)

src/views/CountDetail.vue, src/views/HardCountDetail.vue
#608
Improved the perfomance while scrolling in the normal count.
=> Improved: performance while scrolling in the count (#608)

src/store/modules/product/actions.ts, src/views/CountDetail.vue, src/views/HardCountDetail.vue
#606
- Support for matching products for the identifiers not in goodIdentifications.
- Refetching the product store from the count details page.
- Trimming the trailing space on scanning product.
=> Improved: support for matching of products for the identifiers not in goodIdentifications (#606)

src/views/CountDetail.vue, src/views/HardCountDetail.vue
#606
Used nextTick instead of timeOut in segment change for observer
=> Improved: used nextTick instead of timeOut in segment change for observer (#606)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.5.4)

src/views/CountDetail.vue, src/views/HardCountDetail.vue
#
Fixed loader not dismissing in case of empty hard count
=> Fixed: loader not dismissing in case of empty hard count

package-lock.json, package.json
=> Updated: app version for the minor release (v2.6.0)

src/views/PendingReviewDetail.vue
#635 
- Added loader in the complete count function that completes the pending count.
=> Improved: Added a loader in the complete count function that completes the pending count(#635)

package-lock.json, package.json
=> Improved: package.json & package-lock.json for patch release to 2.6.1

src/views/AssignedDetail.vue, src/views/DraftDetail.vue, src/views/HardCountDetail.vue, src/views/PendingReviewDetail.vue
#642
Passing both productId and idValue for the backend compatibility. IdValue will be removed in the future.
=> Improved: passing productId for backend compatibility in the addProduct api (#642)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.6.2)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.6.3)

package-lock.json, package.json
=> Updated: app version for the patch release (v2.6.4)

src/utils/solrHelper.ts
#
As we are removing some data from solr indexing, so removed this field as well from the query fields on searching
=> Removed: deprecated productCategoryNames field from the queryField list when searching for products

package-lock.json, package.json
=> Updated: app version for the minor release v2.7.0

package-lock.json, package.json
=> Improved: package.json & package-lock.json for patch release to 2.7.1

src/services/UserService.ts, src/store/modules/user/actions.ts
#669
Restricting user to login if no facilitity found associated with user before setting token in state.
=> Improved: restricting user to login if no facilities found before setting token in state (#669)

src/store/modules/count/mutations.ts
=> Fixed: stats not being displayed on the list page

src/components/SelectFacilityModal.vue, src/locales/en.json
#439 
#
Added empty state when searching for facilities on draft detail page.
=> Improved: Added empty state when searching for facilities on draft detail page.(#439)

src/components/Filters.vue
=> Improved: Incorrect Filter Behavior When Selecting Facility and 'No Facility' Together.(#632)

src/store/modules/count/actions.ts, src/views/Draft.vue
#683 
#
After creating a directive draft count, the user is automatically redirected to the count detail page for that count.
=> Implemented: After creating a directive draft count, the user is automatically redirected to the count detail page for that count.(#683)

src/services/CountService.ts
Have updated the service name in Moqui for approve inventory count item to accept inventory count item. Making the needed changes here as well.
=> updated the rest call for acceptItem from approve to accept

src/store/modules/user/actions.ts
#669
Fixed issue revolving around loader not dismissing in case of user without access.
=> Fixed: logout loader not dismissing in case of user without access (#669)

.env.example, src/components/DownloadClosedCountModal.vue, src/services/UserService.ts
=> Implemented: support to save the mappings for the download closed count modal(#710)

package-lock.json, package.json
=> Updated: app version for minor release v2.8.0

src/theme/variables.css
#709
Added padding at the end of the list item.
Before
After
e84)
=> Improved: added paading end to the list item (#709)

src/views/CountDetail.vue
=> Improved: Incorrect tab placement for items which are not counted and rejected by admin in pending review section.(#641)

package-lock.json, package.json
=> Updated: app version for the minor release v3.1.0

package-lock.json, package.json
=> Updated: app version for patch release v3.1.1

package-lock.json, package.json
#774 
#
Improved: Upgraded dxp-components package to v1.22.2 (#774)
=> Improved: Upgraded dxp-components package to v1.22.2 (#774)

package-lock.json, package.json
=> Updated: app version for the minor release v3.2.0

package-lock.json, package.json, src/store/modules/user/actions.ts
#735
- fixed Barcode Identifiers Are Not Listed On Store Permissions Page.
=> Fixed : Barcode Identifiers Are Not Listed On Store Permissions Page (#735)

package-lock.json, package.json, src/store/modules/user/actions.ts
Reverts hotwax/inventory-count#800
=> Revert "Fixed : Barcode Identifiers Are Not Listed On Store Permissions Page (#735)"

src/components/DownloadClosedCountModal.vue, src/utils/index.ts, src/views/AssignedDetail.vue, src/views/ClosedDetail.vue, src/views/DraftDetail.vue, src/views/PendingReviewDetail.vue
#
Fixed: Added checks to filter out voided (soft deleted) cycle count items.
=> Fixed: Added checks to filter out voided (soft deleted) cycle count items.

src/views/CountDetail.vue, src/views/HardCountDetail.vue
=> Fixed: product count increment after item scan and segment navigation(#752)
