- changelogs/unreleased/-1ytrtk0.yml
- src/views/Settings.vue
> Implemented code to display OMS information on settings page(#1ytrtk0)

- changelogs/unreleased/-226cy65.yml
- src/views/Login.vue
- src/views/Search.vue
- src/views/Settings.vue
- src/views/Upload.vue
- src/views/count.vue
> Removed full screen from ion-content in all pages (#226cy65)

- src/views/count.vue
Closes #
when the user selects the stock input field, the system keyboard should be a number pad
> Fixed: Set keyboard type for stock input field(#2cqz21c)

- src/components/ProductListItem.vue
- src/views/count.vue
Closes #127 
Previously we were fetching locations in mounted hook and setting current product in ionViewWillEnter hook. The locations were fetched before the curent product was set. This lead to incorrect data.
Solution: Updated the code to set current product before routing to product detail page.
- [ X] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
> fixed: incorrect facility locations on product detail page(#85zrgfqdj)

- src/views/count.vue
Made the PDP scrollable on shorter to make sure that the input fields aren't hidden behind keyboards and user can always maneuver around the screen.
This needs to be tested, I may have left some syntax issues because I did not build the app.
> PDP is scrollable now

- src/locales/en.json
- src/store/modules/product/actions.ts
- src/views/Upload.vue
> Improved: Added Toast Notification on Item Removal from Upload Page(#213)

- src/store/modules/user/actions.ts
> Fixed: When calling getPermissions api duplicate permissionIds are passed in the payload(#211)

- src/views/count.vue
Closes #265
Improved: Added support to set userLoginId as comments/description while recording variance.
> Improved: Added support to set userLoginId as comments/description while recording variance.

- src/views/Search.vue
https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.
> Fixed: infinite scroll issue when used with searchbar(dxp-289) 

- src/App.vue
- src/components/TabBar.vue
- src/router/index.ts
- src/views/count.vue
As we are not using tab specific routing the page are getting mounted twice in the DOM resulting in having issues when using inline popover components.
Closes #
Improved the routing to use /tabs pattern to correctly create the DOM when using tab-bar
> Fixed: routing in the app to use the tabs/ pattern when using ion-tab-bar

- src/views/Search.vue
https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.
> Fixed: Infinite scroll with searchbar and loading bug(#289)

- src/components/Filters.vue
- src/locales/en.json
- src/store/modules/count/CountState.ts
- src/store/modules/count/actions.ts
- src/store/modules/count/index.ts
- src/store/modules/count/mutations.ts
- src/views/Assigned.vue
- src/views/Closed.vue
- src/views/Draft.vue
- src/views/PendingReview.vue
#
- Added support to select multiple facilities while filtering the counts
- Added check to not display noFacility filter on any page other than draft page
- Added check to disable the filter button when cycleCounts are not found
> Improved: cycle count filters

- src/views/Draft.vue
#
Added support to pass createdDate using the server time when creating a new route, thus removed support to pass created date from app
> Removed: support to pass createdDate when creating a new count

- src/views/CountDetail.vue
#360
- To address the issue where the item list previously did not include the SKU for user searching.
- I added a getter to fetch the SKU of the product from productId and applied the search functionality to it
> Fixed: the searching on products on the count detail page(#360)

- src/views/Tabs.vue
> Fixed: case to always move to count page when moving from settings page in store view screen(#356)

- src/store/modules/user/actions.ts
#352
Fetching the users associated facilities only when user does not have admin screen permission, as in this case we need to display all the facilities for assigning to count.
Related PR: https://github.com/hotwax/inventory-count/pull/383
> Improved: code to fetch only the associated facilities when users does not have admin permissions(#352)

- src/views/ProductDetail.vue
#378 
- Added validation for the input Inventory Count and now it only allows integers.
- Prevent accepting decimal and special characters.
> Improved: added validation on input count of decimals and special characters(#378)

- src/views/ProductItemList.vue
#377 
- Added a quantity check for `0` value in Inventory count.
- The item with a 0 inventory count should be saved correctly and should not appear as pending in the Assigned section.
Before - 
After -
> Improved: item with a 0 inventory count should be saved correctly and will not be pending in the Assigned section(#377)

- src/views/CountDetail.vue
#393 
- Items should be visible when the user switches to any tab and returns to the count section.
- Reset the segment to 'all' & search query when the view is entered
> Fixed: Items should be visible when the user switches to any tab and returns to the count section (#393)

- src/components/Filters.vue
- src/views/Assigned.vue
- src/views/Draft.vue
- src/views/PendingReview.vue
#398
Currently after applying the filter if the counts are not found then the filter becomes disabled. so removed the check to disable the feature always.
Updated the filter label to `Assigned to`
> Improved: label for filters and removed check to disable filters when counts are not found(#398)

- src/views/Count.vue
#396 
- Added bottom padding to the list section of the count that is preventing the overlapping of the tab bar on the last count.
> Fixed: added bottom padding to prevent tab bar overlapping on the last count(#396)

- src/views/ProductDetail.vue
#397 
- Changed the logic to show the toast message "Enter a count before saving changes" when the user attempts to save an empty re-count.
- Additionally, on the re-count screen, the pre-filled quantity value will be shown so that the user knows the previous count of the item and can edit it if needed.
> FIxed: on saving the empty re-count a toast will show-up(#397)

- src/views/ProductDetail.vue
#380 
- So we removed the re-count button when the item status is INV_COUNT_REJECTED or INV_COUNT_COMPLETED.
- Also removed the variance for items in rejected status if the cycle count is in created / assigned status.
- If the item in the cycle count is already counted and can be recounted, we avoid showing the variance of rejected items.
> Improved: added checks on showing variance & re-count button on Product detail section(#380)

- src/views/CountDetail.vue
- src/views/ProductDetail.vue
#353 
- Added sticky scrolling on the counting page.
- Scrolling is working on the items list and the searchbar/ segments are fixed in position.
- The product details section is also not scrolling with list scroll.
> Improved: added sticky scrolling on the counting page(#353)

- src/views/AssignedDetail.vue
- src/views/DraftDetail.vue
- src/views/PendingReviewDetail.vue
#
When renaming a count, user can save the count name even when the name is empty this added check to display a toast when saving an empty count name
> Improved: code to have empty count name while renaming the count

- src/components/CreateMappingModal.vue
- src/locales/en.json
- src/store/modules/count/actions.ts
- src/views/BulkUpload.vue
#
Mapping creation/selection fixes.
> Mapping creation/selection fixes

- src/views/BulkUpload.vue
#
Fixed: Corrected default url for the back button on bulk upload page.
> Fixed: Corrected default url for the back button on bulk upload page.

- src/store/modules/count/actions.ts
- src/views/CountDetail.vue
> Improved: state management on count update and tab change

- src/views/BulkUpload.vue
#457 
- Added code to reset the field mapping.
- After uploading a new file with different columns, the previously mapped fields are reset, and the modal props are also updated, which solves the 4th case.
> Improved: resetting the fieldMapping after every file upload(#457)

- src/store/modules/count/actions.ts
#474 
- Added `backDropDismiss` property as false, which prevent the triggering of any action after and no count record should open unintentionally after the results are fetched.
> Improved: added backdrop property which prevent triggering of any action(#474)

- src/views/Count.vue
> Improved: support to display facilityName or facilityId in the header of store view screen(#440)

- src/views/Count.vue
> Fixed - count name issue (#440)

- src/views/CountDetail.vue
#442 
As we are using indexOf method for finding the product index, but if we already have a current product set, then in that case the product from state is used for finding the index from the filteredItems list, but as the object do not have a common reference, so in this case it always return -1, resulting in buttons being in wrong state.
Improved code to find the selected current product first in the filtered items list and then finding its index, so that it has a common reference.
Before:
Both the buttons are active, even when its the first product.
> Fixed: both the item change buttons becomes active after changing tab(#442)

- src/views/CountDetail.vue
#500
- Center aligned the empty state message "No product found".
- Updated the button for scroll up/down
Before
After
> Fixed: css of the empty state message when no product found and updated the scroll up/down button (#500)

- src/views/CountDetail.vue
#494
Fixed items list not updating properly on saving recount.
> Fixed: wrong updation of cycle count items list on saving recount (#494)

- src/views/CountDetail.vue
#507
- Showing alert on scanning counted item.
- Auto focusing product scan input on confirming on recount alert.
> Improved: showing alert on scanning counted items and autofocusing input on confirming for recount (#507)

- src/locales/en.json
- src/views/CountDetail.vue
- src/views/ProductItemList.vue
- src/views/StorePermissions.vue
#494
-  fetching dynamic good identification from store permissions page.
-  showing 'not counted' for rejected item without quantity
- Reseting inputCount with "" on bringing new product to veiw.
> Improved: fetching dynamic good identification from store permissions page and showing 'not counted' for rejected item without quantity (#494)

- src/views/BulkUpload.vue
#533 
- Added a check to keep the upload button disabled if the saved mapping does not align correctly with the CSV column fields.
> Fixed: For unmatched saved mappings where the required field is empty the user will not be able to upload the file (#533)

- src/store/modules/user/actions.ts
#529 
- Added this change to re-throw the error after logging it because it ensures proper error handling by the calling code.
- Now, a user who does not have the "COMMON_ADMIN" permission and is not associated with any facility will not be able to log in to the application.
> Fixed: Users not associated with any facility will not be able to log in to the app (#529)

- src/views/HardCountDetail.vue
#528
Assigning the value of currentProduct instead of it's ref for proper handling.
> Fixed: ref getting assigned to previous item var (#528)

- src/views/CountDetail.vue
- src/views/HardCountDetail.vue
#528
- Optimized code of CountDetail page.
- Logic to save count of previous selected item if product data came post changing.
- Fixed the handling for the behavior for the update cycle count behavior.
> Improved: added logic to save count of item already counted after product fetching (#528)

- src/components/MatchProductModal.vue
- src/store/modules/product/actions.ts
- src/store/modules/product/mutations.ts
- src/views/HardCountDetail.vue
#528
- Fixed the issue in matching product data manually using match product modal.
- Improved the matched product state handling to add the matched product in the cached state for future use.
> Fixed: match product modal not updating the item data in the state (#528)

- src/locales/en.json
- src/views/HardCount.vue
- src/views/HardCountDetail.vue
#528
- Clearing the hard count component state on leaving the component.
- Added empty state for no facility or facilityGroup in hard count.
- Saving the product count when the unmatched product is matched in the unmatched segment.
> Improved: clearing the hard count component state on leaving the component and added empty state (#528)

- src/locales/en.json
- src/utils/index.ts
- src/views/Assigned.vue
- src/views/AssignedDetail.vue
- src/views/Closed.vue
- src/views/Count.vue
- src/views/CountDetail.vue
- src/views/DraftDetail.vue
- src/views/PendingReview.vue
- src/views/PendingReviewDetail.vue
#555
- Updated the empty state message to be shown when no item is present in the cycle counts in admin screens.
- UI for the count of counted items in the admin screens.
> Improved: empty state in case of no cycle count items and UI for the counted count for hard count (#555)

- src/views/HardCountDetail.vue
#557
Added option to remove the unmatched cycle count items from the hard count.
> Improved: added support for removing the unmatched hard count items from the cycle count (#557)

- src/views/Draft.vue
- src/views/HardCount.vue
#578
Sending below fields while the creation of cycle count for the backend compatitbility.
- uploadedByUserLoginId
- createdDate
> Improved: sending additional field while cycleCount creation for backend compatibility (#578)

- src/views/HardCountDetail.vue
#556
Fixed: scanned count not getting saved when matching manually (#556)
> Fixed: scanned count not getting saved when matching manually (#556)

- src/views/HardCountDetail.vue
#567
Scrolling the first item into view when removing the last item from the cycle count.
> Improved: scrolling to the first element on removing the last item (#567)

- src/components/AssignedCountPopover.vue
- src/views/AssignedDetail.vue
#565
- Showing accepted or rejected label on the items showing the status of the item.
- Added check to hide the remove from count button from the popover.
> Improved: showing accepted or rejected status in the items in the assigned status (#565)

- src/locales/en.json
- src/views/AssignedDetail.vue
- src/views/DraftDetail.vue
- src/views/HardCount.vue
- src/views/PendingReviewDetail.vue
#528
- Fixed count name not updating on UI on successful api call for name updation.
- Sorting by facilityName while fetching the facilities to avoid duplicate facility coming on infinite scrolling.
- Updated the hard count creation page description.
> Fixed: count name not updating on UI post successfull api call and duplicate facility coming on infinite scrolling (#528)

- src/store/modules/count/actions.ts
- src/utils/index.ts
- src/views/AssignedDetail.vue
- src/views/CountDetail.vue
- src/views/DraftDetail.vue
- src/views/HardCountDetail.vue
- src/views/PendingReviewDetail.vue
#602
Implemented sorting based on parentProductName in the cycle Count items
> Implemented: sorting on the cycle count items based on the parentProductName (#602)

- src/views/Count.vue
#605
Fixed the wrong count (total items count) getting displyed in the rejected count item in closed segment.
> Fixed: wrong count displayed in the rejected count item in closed segment (#605)

- src/store/modules/user/actions.ts
- src/views/CountDetail.vue
- src/views/HardCountDetail.vue
#606
- Added permission check over fetching product stores while login.
- Passing product store from current facility while fetching product store settings from details page.
> Improved: added permission check for fetching product stores while login and passing facility store as param while fetching settings (#606)

- src/store/modules/count/actions.ts
#614 
- Added a fix to the `fetchCycleCountsLists` action, ensuring proper handling of the isScrollable variable and toggling it correctly after the final API call.
> Fixed: change the action of fetchCycleCountsLists fixed the extra api calls(#614)

- src/components/DownloadClosedCountModal.vue
#617
When downloading closed count report and if for some product the information is not available from solr, then in that case we get undefined in the item details resulting in jsonToCsv parse failure.
Removed the check for productId when preparing the download and added the check on specific fields value.
If the product information is not available from solr then the downloaded report does not contain any product specific data for that product, so in that case by default added productId from the count
> Fixed: download count issue when product information is not available from solr(#617)

- src/locales/en.json
- src/services/CountService.ts
- src/views/PendingReviewDetail.vue
#635 
- Added a check to prevent completing the pending count as long as any item in the count is in the "created" state. Completion will only be allowed when no items are in the "created" state.
>  Improved: Added a check to allow completing the pending count only when no items are in the "created" state(#635)

- src/App.vue
- src/locales/en.json
#629 
- Previously, on reload, the `onMounted` hook in `App.vue` was running after the `onIonViewWillEnter` hook in the displayed component, which emits the loader event. This caused a mismatch in the sequence of event handling. To address this, the `onMounted` hook was replaced with the `onBeforeMount` hook.  
- Removed the logic of creating the loader from the `onBeforeMount` hook, as it was being handled asynchronously.  
- With these changes, the hook in `App.vue` now runs before the hook in the component, ensuring that the event listener is set up before the loader event is emitted from the component.
> Fixed: On reload of the pending review details page, the loader will remain visible until the items list is updated (#629)

- src/store/modules/count/actions.ts
- src/views/HardCountDetail.vue
#647
Improved code to not add unmatched product in the cached state on saving count.
> Fixed: cached products not getting cleared on saving count (#647)

- src/views/ProductItemList.vue
#646
Product item click not working in case of pending review status of hard count.
> Fixed: item click not working on the pending review for hard count (#646)

- src/store/modules/product/actions.ts
- src/views/HardCountDetail.vue
> Fixed: avoiding refetching of item on adding new item

- src/views/CountDetail.vue
- src/views/HardCountDetail.vue
#655
Added a computeQOH flag in the api for fetching items to compute only if productStore setting to show qoh is true.
> Improved: added a flag for qoh computation while fetching cycle count items (#655)

- src/components/DownloadClosedCountModal.vue
> Improved: code to pass facilityId filter when fetching items for closed count report(#616)

- src/components/Filters.vue
- src/store/modules/count/CountState.ts
- src/store/modules/count/actions.ts
- src/store/modules/count/index.ts
- src/store/modules/count/mutations.ts
- src/utils/index.ts
#619 
- Added Date range filter for cycle counts on the closed page.
- The filter can be applied to the created date and closed date of the cycle counts, with additional checks for dates before and after the created and closed dates.
> Implemented: Date range filter for cycle counts on the closed page (#619)

- src/components/DownloadClosedCountModal.vue
- src/components/SelectFacilityModal.vue
- src/locales/en.json
#616
Added support to download items of the counts considering the filters applied.
> Improved: download closed counts functionality to work with the filters applied (#616)

- src/views/HardCountDetail.vue
#633
Resolved the issue where items with a counted quantity of 0 were not visible in the counted list.
> Fixed: items already counted with 0 qty not visible counted (#633)

- src/locales/en.json
- src/views/Count.vue
#669 
- When no current facility is associated with the user, logging in on the store view page will now trigger a check to prevent fetching cycle counts and display a relevant toast message.
> Improved: Added a check to show a toast when no facility is associated with the user (#669)

- src/views/Closed.vue
#666 
#
Fixed: Search functionality to ensure the search bar remains visible in the 'Closed' tab, even when no match is found.(#666)
> Fixed: Search functionality to ensure the search bar remains visible in the 'Closed' tab, even when no match is found.(#666)

- src/components/MatchProductModal.vue
#528
Fixed the UI behaviour of the match product modal in different searching scenarios
> Fixed: UI of the match product modal on different scenarios (#528)

- src/store/modules/count/actions.ts
- src/views/HardCountDetail.vue
#667 
#
Delete product icon now disappears.
Unmatched products are now permanently deleted from the hard count when removed all at once.
> Fixed: Delete product icon now disappears and Unmatched products are now permanently deleted from the hard count when removed all at once.

- src/store/modules/user/actions.ts
#
Fixed: Unable to login into the app when used is having admin permission, but no facility is associated with the user.
> Fixed: case to directly check admin permission instead of using hasPermission method

- src/views/DraftDetail.vue
- src/views/PendingReviewDetail.vue
#689 
- The count that was created without a cycle count name or if the cycle count name does not exist can now be updated by the user
> Fixed: User is now able to rename the unnamed cycle count (#689)

- src/components/Filters.vue
#586 
- Removed the restriction of displaying selected facilities only in the Filters on the Closed page.  
- The selected facility is now visible across all pages, including Draft, Assigned, and Pending Review, within the Filter.
> Improved: Selected facility name is consistent across all pages in Filters (#586)

- src/views/ProductItemList.vue
> Fixed: Secondary Product Identifier of First Product Appears in Bold Color on Store View Screen.(#468)

- src/components/Filters.vue
- src/components/SearchBarAndSortBy.vue
- src/locales/en.json
- src/store/modules/count/actions.ts
- src/store/modules/count/index.ts
- src/store/modules/count/mutations.ts
- src/theme/variables.css
- src/views/Assigned.vue
- src/views/Closed.vue
- src/views/Draft.vue
- src/views/PendingReview.vue
#631
- Previously, the `Sort By` filtering was present in the `Filters` section on various pages. This filtering included sorting by `due date` and `alphabetically`.  
- Now I have added the `Sort By` option adjacent to the search bar. It now includes three options: `Created Date` (default), `Due Date`, and `Alphabetical`.  
- The `Created Date` sorting arranges the cycle count in `descending order`, meaning the most recently created items appear at the top of the list. The same pattern is applied to `Due Date` sorting.
> Implemented: Added a Sort By filter for Created Date, Due Date, and Alphabetical sorting on the Draft, Assigned, Pending review and closed page(#631)

- src/store/modules/count/actions.ts
#682 
- Added support for applying date filters while fetching the closed count.  
- Also updated the `statusId` field and included `INV_COUNT_REJECTED` while fetching the closed count, as this status is only added to the query during the initial fetch after landing on the page.  
- Additionally, added the same check for including `INV_COUNT_REJECTED` in both the `statusId` and the `statusId` operator condition while fetching the closed cycle count after applying filters.
> Improved: Added support to fetch the total closed count after applying date filters (#682)

- src/store/modules/count/mutations.ts
#631
- Changed dueDate sorting to ascending (asc) when clearing the count query; it was previously set to descending (desc).
> Improved: Added ascending dueDate sorting when clearing the count query(#631)

- src/views/CountDetail.vue
- src/views/ProductItemList.vue
#738
- Previously, we only controlled the snap scrolling effect of the images on the `Hard Count Detail page`.
- Added the same support on the `Count Details page` as well. Now, turning off the `Scrolling Animation` toggle from the Settings will also disable the scrolling effect on the Count Details page.
> Implemented: Added support to handle the image scroll effect using the scrolling toggle on the Settings page (#738)

- src/views/CountDetail.vue
#771 
- Added a check to prevent the update count alert box from opening in the Pending Review and Closed sections on the store view side of the Inventory app.
> Fixed: Added a check to prevent the update count alert box from opening in the Pending Review and Closed sections (#771)

- firebase.json
#104
#
Improved: Used frame-ancestors in CSP security header instead of X-Frame-Options (https://github.com/hotwax/fulfillment/pull/104).
> Improved: Used frame-ancestors in CSP security header instead of X-Frame-Options (#104).

- src/store/modules/count/actions.ts
- src/utils/indexeddb.ts
- src/views/AssignedDetail.vue
#778
- Added support to set statusId to `INV_COUNT_VOIDED` on item soft delete
- Excluded voided items from the count details page on the store view side
- Removed voided items from IndexedDB after receiving soft delete from the admin side
> Implemented: added support for soft-deleting an item from the assigned details page (#778)

- src/components/MatchProductModal.vue
#795 
Fixed: Getting and displaying the product as result based on the query  by not fully depending on the cached product which is fetched earlier
> Fixed:fixed the missing identifier from match modal(#795)
